# Generated by Django 5.2.7 on 2025-10-11 21:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0003_conference_remove_submission_papers_submission_paper_and_more'),
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ConferenceApp.conference'),
        ),
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_room_name', message='Le nom de la salle ne doit contenir que des lettres et des chiffres.', regex='^[A-Za-z0-9]+$')]),
        ),
    ]
