# Generated by Django 5.2.7 on 2025-10-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0003_conference_remove_submission_papers_submission_paper_and_more'),
        ('SessionApp', '0002_alter_session_conference_alter_session_room'),
        ('UserApp', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conferance',
        ),
    ]
