# Generated by Django 5.2.7 on 2025-10-24 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(30, 'vous avez utuliser la limite des mots autorisés')]),
        ),
    ]
