# Generated by Django 5.2.7 on 2025-10-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
